class STYLESHEET:
    @staticmethod
    def MAIN():
        SHEET='''QWidget{
        background-color:blue; border-radius:20px;
        }      
        '''
        return SHEET

    @staticmethod
    def GroupBox():
        SHEET = '''QGroupBox
        {
        background-color: rgb(0, 255, 255); border: 2px solid green;
        border-radius: 20px;
        }     
                '''
        return SHEET
